server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;
    port_in_redirect off;

    location /gateway/ {
        proxy_pass http://gateway:5550/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = / {
        try_files /ui-resume/index.html =404;
    }

    location = /index.html {
        try_files /ui-resume/index.html =404;
    }

    location /ui-resume/ {
        try_files $uri $uri/ /ui-resume/index.html;
    }

    location / {
        try_files $uri $uri/ /ui-resume$uri /ui-resume/index.html;
    }
}
